#!/usr/bin/env python3
"""gen_docs.py — render the human-facing foundation docs FROM the manifest.
Never hand-edit these; edit canon, re-scan, re-render. Keeps prose and machine state in lockstep."""
import json, pathlib, sys, datetime as dt
# gen_docs renders docs FROM a StoryOS state file into that same install dir.
# Usage: gen_docs.py [install_dir]   (default: this repo's install/soul_land_4)
root = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else \
    pathlib.Path(__file__).resolve().parent.parent / "install" / "soul_land_4"
_mf = root / "STORYOS_STATE.json"
if not _mf.exists():
    _mf = root / "foundation" / "CURRENT_STATE_MANIFEST.json"
M = json.loads(_mf.read_text(encoding="utf-8"))
E, C = M["edge"], M["characters"]
today = dt.date.today().isoformat()

def tbl(rows, head):
    return "| " + " | ".join(head) + " |\n|" + "|".join(["---"]*len(head)) + "|\n" + \
           "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)

# ---------------- STATUS_PANEL.md ----------------
ch_rows = [(n, c.get("dorm"), c.get("rank","—"), c.get("sp","—"),
            (c.get("state") or "")[:200]) for n,c in sorted(C.items(), key=lambda kv:str(kv[0]))]
yan = C.get("Yan Shuo", {})
fw = [(f["character"], f["topic"], f["state"], f["rule"][:160]) for f in M["knowledge_firewalls"]]
lock_rows = []
for card in sorted((root/"canon/locks").glob("*.card.md")):
    txt = card.read_text()
    st = [l for l in txt.splitlines() if l and not l.startswith(("#","```","{","}","    ","Generated"))]
    lock_rows.append((card.stem.replace(".card",""), (st[0] if st else "")[:170]))
panel = f"""# Status Panel — {M['project']}

> Generated by `scripts/gen_docs.py` from `foundation/CURRENT_STATE_MANIFEST.json` on {today}.
> This is the machine-derived live state. Do not hand-edit; change canon, then re-scan + re-render.

**Live edge: after Chapter{E['fic_chapter']}, `{E['fic_title']}`** — declared by `{E['declared_by']}` on {E['declared_on']}.

| Field | Value |
|---|---|
| Canon consumed through | Chapter{E.get('canon_consumed')} `{E.get('canon_consumed_title')}` |
| Next source boundary | Chapter{E.get('next_source')} `{E.get('next_source_title')}` |
| Accepted fic chapters | {len(E.get('accepted_chapters', []))} |
| Quarantined chapters | {M['metrics']['quarantined_chapters']} (superseded branch) |
| Information discipline | {M['information_discipline']} |
| Pacing mode | `{M['pacing']['mode']}` |

## 1. Next-chapter guard

1. Fetch **all** chunks of canon Chapter{E.get('next_source')} `{E.get('next_source_title')}` before drafting.
2. Write `canon_coverage/Canon_Coverage_Chapter_{E['fic_chapter']+1}.md` **before** prose.
3. Preserve locked states below unless the source explicitly changes them.
4. Do not consume Chapter{(E.get('next_source') or 0)+1} material early.
5. Run `python3 tools/storyos_validate.py --project . --phase pre` before blueprinting,
   `--phase post --files chapters/Chapter_{E['fic_chapter']+1}.md` after drafting.

## 2. Characters (current locked state)

{tbl(ch_rows, ["Name","Dorm","Rank","SP","State"])}

## 3. {yan and 'Yan Shuo — protected power sheet' or 'Power sheet'}

{tbl([(k, v[:230]) for k, v in (yan.get('sheet') or {}).items()], ["Aspect","Locked state"])}

- **Power floor:** {yan.get('power_floor','—')}
- **Power ceiling:** {yan.get('power_ceiling','—')}
- **Public identity:** {yan.get('public_identity','—')} · **Reveal status:** {yan.get('reveal_status','none')}

## 4. Knowledge firewalls

{tbl(fw, ["Character","Topic","State","Rule"])}

## 5. Regression tokens — must never appear in prose as current fact

`{'`, `'.join(M.get('enforce', []))}`

Advisory (review on sight, not auto-fail): {len(M.get('advisory_review', []))} terms — see `foundation/BANNED_TOKENS.json`.

## 6. Locks on record ({len(lock_rows)})

{tbl(lock_rows[:60], ["Lock card","Statement"])}

## 7. Stale claims under supervision

{chr(10).join('- ' + s for s in M['stale_claims']) or '- none'}

Superseded receipts are marked `SUPERSEDED — DO NOT USE` in `audits/` and copied to
`archive/quarantine/`. The validator treats an **unmarked** live-status claim from a dead
branch as an error; a marked one is informational.
"""
(root/"STATUS_PANEL.md").write_text(panel)

# ---------------- NO_MISTAKE_LIVE_RULES.md ----------------
rules = f"""# NO_MISTAKE_LIVE_RULES — universal canon discipline

Generated {today}. Rules carry stable IDs so an agent can cite *why* it refused a beat.
Any rule below was created by a real failure the user already rejected once.

## Core operating rules
- **R01** The control centre / status panel is a *mirror* of project state, never an authority over it.
- **R02** Do not treat author knowledge as character knowledge.
- **R03** Do not invent missing canon. If a source scene is absent, name it missing.
- **R04** Preserve established decisions unless the user explicitly authorizes change.
- **R05** Never leak rejected drafts into active canon.

## Canon and butterfly
- **R06** Canon-first. Butterfly effects must grow from actual changed events.
- **R07** One canon episode = one operational unit of *consequence*, not of word count.
- **R08** Do not invent formal reward ceremonies or items just to prove a butterfly consequence.

## Information discipline
- **R09** Track every fact as KNOWN / SUSPECTED / UNKNOWN / FALSE BELIEF / KNOWN PARTLY / DISBELIEF / HIDDEN.
- **R10** Never convert suspicion, intuition, rumour, prophecy fragments, or author knowledge into factual character knowledge without on-page evidence.
- **R11** Do not give a character information earlier than the earliest valid change recorded in their firewall entry.
- **R12** Secrets between bonded characters are safety boundaries imposed by adults or circumstance — not evidence of distrust.

## Power discipline
- **R13** Do not nerf or inflate a character to force the OC plot.
- **R14** Where a baseline/floor is locked, count the full established foundation before ranking anyone below it.
- **R15** Do not use in-world excuses (admin, scanner, records) to hide a strength hierarchy the reader can see.
- **R16** Adaptation-type personal frameworks are innate, non-conscious, existence-level law — never a UI, voice, companion, reward system, or generic learning mechanic. They cannot create power from nothing or bypass setting rules.

## Craft and pacing
- **R17** Preserve competent canon characterization.
- **R18** Compress routine source beats; expand only meaningful character / system / butterfly / relationship / tactical change.
- **R19** Do not replace detailed codex files with short summaries. Add a summary file; never overwrite detail.
- **R20** After any rejection, repair the *direction*, then re-derive state — do not continue as if unnotified.

## Process gates
- **R21** Pre-draft gate is mandatory: LOAD → VERIFY → MAP, then state confirmed / missing / must-reconstruct **before** prose.
- **R22** `storyos_validate.py --phase pre` must report no errors before blueprinting.
- **R23** `storyos_validate.py --phase post --files <new chapter>` must pass before presenting.
- **R24** Record new decisions and corrections as lock cards so they cannot regress later.

## Continuation protocol
1. Re-scan state: `python3 scripts/scan_project.py <corpus> .`
2. Read `foundation/STATUS_PANEL.md`, then this file, then the relevant `codex/` files.
3. Run `--phase pre`. Resolve every `error`.
4. Write coverage file for the new chapter **before** prose.
5. Draft using R18 pacing, obeying R09–R13.
6. Run `--phase post --files chapters/Chapter_N.md`.
7. Re-scan, re-render docs, rebuild the control centre, record the receipt.
"""
(root/"NO_MISTAKE_LIVE_RULES.md").write_text(rules)

# ---------------- CANON_SOURCE_NUMBERING_MAP.md ----------------
num = [(r["fic"], r["canon"], r["status"], r.get("validation") or "—") for r in M["canon_numbering"]]
(root/"CANON_SOURCE_NUMBERING_MAP.md").write_text(
 f"""# Canon Source Numbering Map

Generated {today}. fic chapter ↔ consumed canon source, with the receipt proving it.
`quarantined-superseded` rows are evidence of a rejected attempt and are **not** a starting point.

{tbl(num, ["Fic","Canon source","Status","Validation receipt"])}

**Boundary:** consumed through Chapter{E.get('canon_consumed')}; next Chapter{E.get('next_source')}.
Never consume beyond the boundary without a new coverage file and an accepted validation receipt.
""")
print("wrote: foundation/STATUS_PANEL.md, NO_MISTAKE_LIVE_RULES.md, CANON_SOURCE_NUMBERING_MAP.md")
print("STATUS_PANEL:", len(panel), "chars · rules file:", len(rules), "chars · numbering rows:", len(num))
